### ISSUE TITLE
Klargøring af opgave repository

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/dev-polyglot-microservices#3]
Ansættelsesudvalget ønsker at kunne stille en relevant opgave til ansøgerne, så de kan bevise om de kan arbejde med de værktøjer og metoder, vi bruger i udviklingsafdelingen og så udvalget har en mulighed for at vurdere deres tekniske niveua.
```[tasklist]
### Tasks
- [ ] https://github.com/Randers-Kommune-Digitalisering/dev-polyglot-microservices/issues/5
- [ ] https://github.com/Randers-Kommune-Digitalisering/dev-polyglot-microservices/issues/6
- [ ] Opgavebeskrivelse skal skrives rent @tna-randers
- [ ] ~~README.md skal opdateres med opgavebeskrivelse~~ Opgavebeskrivelse sendes med mail @tna-randers
- [x] HOW TO skrives med guide til at starte et code-space op (inkl. guide til docker kommandoer, som i vores alm. Node-red template repo)
- [x] Beslutning: Skal der laves ET eller flere repos? - Der laves ET og ansøgere kloner selv til deres egen konto
- [ ] repo godkendes inden ny template skabes
- [ ] https://github.com/Randers-Kommune-Digitalisering/dev-polyglot-microservices/issues/4
```

**Comment by tna-randers** [comment]
Opgave

I Randers Kommune er der udpeget en række medarbejdere, som har brug for data til forskellige former for ledelsesinformation. Disse medarbejdere betjener værktøjer, hvor data er klargjort (konverteret og modelleret) til brug primært i vores open source datavisualiseringsværktøj Apache Superset eller vores SAP Business Objects. Opgaven med at konvertere og modellere data ligger altså pt. hos udviklerne. 

I forbindelse med planlægning af nye udstykninger til lejligheder er der et ønske om at følge udviklingen i civilstand for både mænd og kvinder i alderen 20 til 90 år i kommunen. Data omkring dette findes her: https://www.statistikbanken.dk/FOLK1A

Disse data ønskes klargjort i en MariaDB database. Der ønskes opdaterede data 7 dage efter start af hvert kvartal. 

Tag inspiration fra den OpenData connector der er gjort tilgængelig i skabelonen og skab en genbrugelig, generisk connector der kan trække data ned fra statistikbankens API. Læs mere om brug af API-et her: https://www.dst.dk/da/Statistik/brug-statistikken/muligheder-i-statistikbanken/api

Der kan sagtens komme flere lignende projekter, så du må gerne overveje, hvordan løsningen kan genbruges i andre projekter.

**Comment by tna-randers** [comment]
Løsningen afleveres ved at overføre ejerskabet af dit repository til Github brugeren tna-randers. Læs mere om overførsel af ejerskab her: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

Efter samtalen overfører vi ejerskabet tilbage til dig.

**Comment by ghost** [comment]
Skabelonen understøtter at løsningen kan udvikles i en bred vifte af udviklings og logiske udtryks sprog.

Orkestrering og flow/event styring køres i Node-RED.

Der kan udvikles forretningslogik med Native Node-RED nodes, javascript, JSONata og Mustache.

Foretrækker man python, ligger der en færdigbygget microservice skabelon og en redis kømotor.

Til R og C# er der et par HTTP REST baserede færdigbyggede microservices.

Ønsker man at lave logik i et andet sprog som f.eks Rust, Go, Julia eller andre, kan man selv bygge en container inkl. dependencies og en kommunikations protokol.

Aflevering af data sker med standard SQL til en MariaDB database service inluderet i skabelonen

**Comment by kf-randers** [comment]
Forslag til rettelser

- Det forventes ikke, at du bruger mere end 4 timer på opgaven
- Formålet med opgaven er ikke nødvendigvis at du når i mål, men at du kan demonstrere at du kan bruge dem og dele dine reflektioner til samtalen
- Du forventes at løse opgaven alene...
